ESTADO_INICIO = "INICIO"
ESTADO_IDENTIFICANDO_CLIENTE = "IDENTIFICANDO_CLIENTE"
ESTADO_MENU = "MENU"
ESTADO_ESCOLHENDO_PRODUTOS = "ESCOLHENDO_PRODUTOS"
ESTADO_CONFIRMAR_PEDIDO = "CONFIRMANDO_PEDIDO"
ESTADO_CONFIRMAR_ENDERECO = "CONFIRMANDO_ENDERECO"
ESTADO_ESCOLHER_PAGAMENTO = "ESCOLHENDO_PAGAMENTO"
ESTADO_PEDIDO_CRIADO = "PEDIDO_CRIADO"
ESTADO_CONSULTANDO_PEDIDO = "CONSULTANDO_PEDIDO"
ESTADO_ATENDIMENTO_HUMANO = "ATENDIMENTO_HUMANO"
ESTADO_AGUARDANDO_NOME = "AGUARDANDO_NOME"
ESTADO_AGUARDANDO_DOCUMENTO = "AGUARDANDO_DOCUMENTO"


TRANSICOES_PERMITIDAS = {
    ESTADO_INICIO: {
        ESTADO_MENU,
        ESTADO_AGUARDANDO_NOME,
    },
    ESTADO_IDENTIFICANDO_CLIENTE: {
        ESTADO_MENU,
        ESTADO_AGUARDANDO_NOME,
    },
    ESTADO_AGUARDANDO_NOME: {
        ESTADO_MENU,
    },
    ESTADO_MENU: {
        ESTADO_ESCOLHENDO_PRODUTOS,
        ESTADO_CONSULTANDO_PEDIDO,
        ESTADO_ATENDIMENTO_HUMANO,
    },
    ESTADO_ESCOLHENDO_PRODUTOS: {
        ESTADO_ESCOLHENDO_PRODUTOS,
        ESTADO_CONFIRMAR_PEDIDO,
    },
    ESTADO_CONFIRMAR_PEDIDO: {
        ESTADO_ESCOLHENDO_PRODUTOS,
        ESTADO_CONFIRMAR_ENDERECO,
        ESTADO_MENU,
    },
    ESTADO_CONFIRMAR_ENDERECO: {
        ESTADO_ESCOLHER_PAGAMENTO,
        ESTADO_CONFIRMAR_PEDIDO,
    },
    ESTADO_ESCOLHER_PAGAMENTO: {
    ESTADO_PEDIDO_CRIADO,
    ESTADO_AGUARDANDO_DOCUMENTO,
},
    ESTADO_PEDIDO_CRIADO: {
        ESTADO_CONSULTANDO_PEDIDO,
        ESTADO_MENU,
    },
    ESTADO_CONSULTANDO_PEDIDO: {
        ESTADO_MENU,
    },
    ESTADO_ATENDIMENTO_HUMANO: {
        ESTADO_MENU,
    },
    ESTADO_AGUARDANDO_DOCUMENTO: {
        ESTADO_ESCOLHER_PAGAMENTO,
}
}